import Head from "next/head";
import CategoriesList from "../components/CategoriesList";
import Header from "../components/Header";
import PostCard from "../components/PostCard";
import RecentPosts from "../components/RecentPosts";
import { getPosts } from "../services";
export default function Home({ posts }) {
  console.log(posts);
  return (
    <div>
      <Head>
        <title>CMS blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="container grid grid-cols-1 gap-12 mx-auto lg:grid-cols-12">
        <div className="col-span-1 lg:col-span-8">
          {posts.map((each, index) => (
            <PostCard post={each} key={index} />
          ))}
        </div>
        <div className="lg:col-span-4 col-span-1 ">
          <div className="lg:sticky top-8">
            <RecentPosts />
            <CategoriesList />
          </div>
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const posts = (await getPosts()) || [];
  return {
    props: { posts },
  };
}
